makefile.cargo
There was a problem that the MSYS-dependent routine relies on
`$(TARGET)` rather than `$(HOST)`.
Fixes #42.
=> Fix Windows cross-compilation

src/lib.rs
[Originally defined in hb-unicode.h](https://github.com/servo/rust-harfbuzz/blob/master/harfbuzz/src/hb-unicode.h#L222-L247)
r? @metajack
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/48)
=> Add unicode_*_func_t callback types

build.rs, makefile.cargo
In some cases cross compilation fails with harfbuzz, this fixes the issue. 
Part of servo/servo#6327
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/50)
=> Allow to override CC and AR for cross compilation.

.travis.yml, harfbuzz-sys/Cargo.toml, harfbuzz-sys/makefile.cargo
Fixes #54, fixes servo/servo#8890.
r? @larsbergstrom or @metajack
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/58)
=> Move touch command into makefile.cargo

.travis.yml, harfbuzz-sys/Cargo.toml, harfbuzz-sys/makefile.cargo
This reverts #58.  The patch worked fine when building from git but broke when published to crates.io, because `cargo publish` does not package files in the `exclude` list. :(
r? @metajack
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/60)
=> Revert "Move touch command into makefile.cargo"

harfbuzz-sys/makefile.cargo
This enable support for mort and morx ligatures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/61)
=> Compile --with-coretext on apple-darwin (see servo/servo#4320)

harfbuzz-sys/Cargo.toml, harfbuzz-sys/build.rs, harfbuzz-sys/harfbuzz/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/63)
=> [msvc] Convert from make to cmake for native Windows builds

harfbuzz-sys/Cargo.toml, harfbuzz-sys/makefile.cargo
r? @mbrubeck 
The issue here is that now that we're not using the NDK toolchain, the compilers won't "magically" figure out all of the include paths. These have all been set up in `CXXINCLUDE` but we need to pass them to `CPPINCLUDE` in order for the C preprocessor to also be able to pick up the hodge-podge of include directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/68)
=> Fix android

harfbuzz-sys/build.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/73)
=> Set Cargo metadata so dependents can find hb.h

harfbuzz-sys/src/lib.rs
Due to the `#foo` syntax in the doc comments, if the `#` was at the
start of the line, the 2 different markdown implementations were
interpreting that differently, resulting in a new warning when
building the docs.
This changes all occurrences of this syntax, but doesn't address
broader issues of the markdown formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/87)
=> Fix pulldown / markdown warning with current rustc.

README.md
The crate documentation link already points to docs.rs, so this
brings the README into line with that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/84)
=> README: Point to docs.rs.

harfbuzz-sys/src/lib.rs
This fixes the warning that shows up in `cargo test`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/85)
=> Fix non_snake_case warning in test.

harfbuzz-sys/Cargo.toml, harfbuzz-sys/src/lib.rs
This is a breaking change.
Fixes issue #88.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/91)
=> [breaking change] Use ::std::os::raw instead of libc.

harfbuzz-sys/src/lib.rs
This fixes warnings under clippy, but also happily makes it match
how current bindgen generates code, which will reduce some diffs
that will be coming up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/92)
=> Derive Clone rather than impl it.

harfbuzz-sys/src/lib.rs
The code generated by bindgen doesn't follow this guideline, so we'll
disable that check here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/94)
=> Disable clippy warning for unreadable_literal.

harfbuzz-sys/src/lib.rs
Current versions of `bindgen` run `rustfmt` on the generated code, so this makes it easier to compare diffs and get subsequent things merged and landed by themselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/93)
=> Run rustfmt.

harfbuzz-sys/src/lib.rs
This brings us up to how current versions of bindgen generate
this construct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/95)
=> Use ::std::ptr::null instead of literal 0.

harfbuzz-sys/src/lib.rs
The version constants were for the version of the library that
was present when the bindings were generated, not the version
that is actually present at runtime. Checks should be done against
the version present at runtime using `hb_version_*`.
This is a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/96)
=> [breaking change] No longer provide HB_VERSION_*.

harfbuzz-sys/src/lib.rs
`hb-ot.h` isn't included by `hb.h`, so bindings for the OpenType APIs weren't being generated. This corrects that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/102)
=> Add hb_ot_* bindings.

harfbuzz-sys/src/lib.rs
`hb_font_funcs_set_glyph_func` and `hb_set_invert` have been deprecated
so we don't want to bind them and encourage people to use them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/103)
=> Remove deprecated functions.

.gitignore, Cargo.toml, harfbuzz/Cargo.toml, harfbuzz/src/buffer.rs, harfbuzz/src/direction.rs, harfbuzz/src/language.rs, harfbuzz/src/lib.rs
There is an orphaned crate, https://crates.io/crates/harfbuzz. This was previously published by the Servo project, but now the Servo project really only maintains `harfbuzz-sys` which doesn't present a safe API.
This is proposing adding back a `harfbuzz` crate that could be used by Servo and other projects, but would be safe and have somewhat better ergonomics.
This also would address my question from issue #90 about using `enum` and bit flags.
Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/105)
=> Add a new safe harfbuzz crate.

harfbuzz/src/buffer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/111)
=> impl Clone for Buffer

harfbuzz/src/buffer.rs, harfbuzz/src/language.rs
This is necessary for safety; otherwise safe Rust code could cause memory-safety violations by writing to the `raw` field and then calling safe methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/110)
=> [breaking change] Make raw pointer fields private

harfbuzz/src/blob.rs, harfbuzz/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/109)
=> Add wrapper for hb_blob_t

harfbuzz/src/blob.rs, harfbuzz/src/buffer.rs
Reverts #111.
I realized that allowing these types to be cloned makes it impossible to provide safe borrowed access to their contents, because one handle could mutate or clear the contents while they are borrowed through another handle.
Rust code that needs multiple pointers to a single buffer or blob should use Rc/Arc or `&T` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/113)
=> Remove Clone impls for Buffer and Blob

harfbuzz/src/language.rs
This also fixes a clippy warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/124)
=> Make Language Copy/Clone.

harfbuzz-sys/src/lib.rs
This requires harfbuzz 2.2.0 as the header is new there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/127)
=> harfbuzz-sys: Add bindings from hb-aat.h.

harfbuzz-sys/makefile.cargo
The library is missing coretext features on macos; this manifests
in the travis build for wezterm here:
https://travis-ci.org/wez/wezterm/jobs/497309625
```
"_hb_coretext_font_create", referenced from:
wezterm::font::hbwrap::Font::new_coretext::hd071aafeac2e8295 in wezterm-0dd706f6ee97bf14.10pwsdaw58utpw8o.rcgu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Inspecting the output of the build shows that configure is being invoked this way:
```
cd /Users/wez/src/wezterm/target/debug/build/harfbuzz-sys-0ec3b8d6c31c3064/out && /Users/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbu
zz-sys-0.3.0/harfbuzz/configure --prefix=/Users/wez/src/wezterm/target/debug/build/harfbuzz-sys-0ec3b8d6c31c3064/out …
```
=> fixup compilation of libharfbuzz on macos

harfbuzz-sys/Cargo.toml, harfbuzz-sys/build.rs, harfbuzz/Cargo.toml
- Declare default features "build-native-harfbuzz" and "build-native-freetype".
- Make the pkg-config and cmake build-dependencies optional.
- Make build.rs a no-op if "build-native-harfbuzz" is disabled.
These changes allow the library to be used in projects where the native harfbuzz and freetype librares are built separately, and where cmake and pkg-config are not supported.
Depends on servo/rust-freetype#57.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/129)
=> Add "build-native-harfbuzz" and "build-native-freetype" features

harfbuzz-sys/Cargo.toml, harfbuzz-sys/src/coretext.rs, harfbuzz-sys/src/lib.rs
This adds a macOS-only dependency upon core_graphics, core_text,
and foreign_types, so that we can interop with the CGFontRef
and CTFontRef values from the existing core_graphics and core_text
bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/133)
=> macOS: Add bindings for hb-coretext functions.

harfbuzz/src/blob.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/135)
=> Add blob wrapper for Arc<Vec<u8>>

harfbuzz-sys/Cargo.toml
The crates.io limit is 10mb, but the latest package is 20mb. The test data is 32mb out of 43mb uncompressed, and the crate builds fine without it. The final package size is 2.2mb.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/136)
=> Exclude test data from published crate.

harfbuzz-sys/build.rs
In order to build a Rust crate with C/C++ that uses the HarfBuzz library referenced by the `harfbuzz` crate, I need to know where the header files are. I believe the standard way of doing that is the `links` key/value environment variables. In particular, I'm expecting `DEP_HARFBUZZ_INCLUDE` to tell me the include path for `hb.h` and other header files. Unfortunately, this doesn't seem to be working correctly now. This PR is an attempt to resolve that.
Summary of changes:
* Prints proper values for `cargo:include` in the build script for both the `pkg-config` and vendored cases.
* Changes a use of `to_str().unwrap()` to `PathBuf::display()`. I believe this is better, but I'm happy to be corrected.
As far as adding a useful feature goes, I think this PR is complete. However, there are a …
=> Print proper cargo:include values

.travis.yml, Cargo.toml, harfbuzz-sys-test/Cargo.toml, harfbuzz-sys-test/build.rs, harfbuzz-sys-test/src/main.rs, harfbuzz-sys/src/lib.rs
This adds a crate to the workspace for testing `harfbuzz-sys` automatically using `ctest`.
I changed a few types in `harfbuzz-sys/src/lib.rs` to make the testing automatic (i.e. to avoid creating special cases). However, I suppose `lib.rs` is generated? If so, this might be problematic if it is regenerated later. The changes seem quite sensible to me, so maybe there's an alternative to tweak the generation to get something similar?
`harfbuzz-sys-test` currently only works with `HARFBUZZ_SYS_NO_PKG_CONFIG=1` because it doesn't get the `DEP_HARFBUZZ_INCLUDE` environment variable otherwise. The `.travis.yml` change reflects that. If #139 or something similar is merged, this special case can be removed, and the test should be run for both `HARFBUZZ_SYS_NO_PKG_CONFIG=1` and without …
=> Add harfbuzz-sys-test using ctest

harfbuzz-sys/Cargo.toml
This is a key part taken from #138 and #142. I'm creating a new PR here for just this since those others have been combined with other, somewhat orthogonal issues. I think it's best to go ahead and merge this and make a release, since this issue is affecting others. I'll continue working on the other issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/144)
=> Exclude only test font data

.travis.yml, harfbuzz-sys/makefile.cargo
`cargo package` sporadically complains about file modifications outside `OUT_DIR`. See https://github.com/servo/rust-harfbuzz/pull/142 for an experiment with chasing down that issue, which can involve different files changed at different times.
The build script is written to build out-of-tree in `OUT_DIR`, but `configure` and/or `make` still modify the source tree.
This change involves creating a temporary `BUILD_DIR` in `OUT_DIR`, copying the source files there, building, installing into `OUT_DIR`, and, finally, removing `BUILD_DIR`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/147)
=> Avoid source changes during static build

harfbuzz-sys-test/build.rs, harfbuzz-sys/build.rs
I introduced this in 692048e56a66afc36d4a6ef261ed2965bdcdf30a, but it's the wrong thing to do. When a dependent crate gets the `pkg-config` include paths in `DEP_HARFBUZZ_INCLUDE`, it may also need other aspects such as the link paths, but it doesn't know that information is available from `pkg-config`. So, the dependent crate must assume that, if `DEP_HARFBUZZ_INCLUDE` is not available, it should use `pkg-config`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/148)
=> Don't print cargo:include= with pkg-config

harfbuzz-sys/build.rs
This supports building harfbuzz-sys for WebAssembly using:
--target wasm32-unknown-unknown --features=build-native-harfbuzz
Building with emscripten may or may not work yet.
This is progress on issue #153.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/155)
=> Preliminary build support for WebAssembly.

appveyor.yml, harfbuzz-sys-test/Cargo.toml, harfbuzz-sys-test/src/main.rs
The generated code depends upon libc, so make that explicit here.
Not sure why this worked before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/159)
=> Fix harfbuzz-sys-test compilation with nightly.

.travis.yml
This is required to get the current versions of Harfbuzz that are
bundled, so that ctest will check against those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/163)
=> Update homebrew on Travis.

harfbuzz-sys/Cargo.toml, harfbuzz-sys/src/lib.rs
For all Apple platforms, we want to be linking against CoreFoundation
and CoreText, and not FreeType.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/169)
=> Improve deps for Apple platforms.

harfbuzz-sys/Cargo.toml, harfbuzz-sys/makefile.touch
This is untested, but hopefully works around https://github.com/servo/servo/issues/24611.
This is not suitable for development of Harfbuzz itself (as opposed to bindings), but hopefully that doesn’t happen in this repository and being required to run `cargo clean` after updating the Harfbuzz version is acceptable.
=> Never run ragel when generated files exist

harfbuzz-sys/Cargo.toml, harfbuzz-sys/build.rs
This is a test to see what happens if we switch to using the unity build for harfbuzz.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/170)
=> Experimental change to use harfbuzz unity build.

harfbuzz-sys/Cargo.toml
This allows coverage using lcov and grcov. Related to this issue https://github.com/servo/core-foundation-rs/pull/357
=> Upgrade core libs

harfbuzz-sys/Cargo.toml, harfbuzz/Cargo.toml
Therefore change feature name to match upstream's:
https://github.com/servo/rust-freetype/commit/342ad76e12b9792bf400a11a749032274188605b
Also bump version of harfbuzz-sys to 0.4 like in PR #107.
=> Update to freetype 0.5

harfbuzz-sys/build.rs
When building on window-gnu targets I was getting "file too big errors" in harfbuzz-sys. This adds the assembler flag -mbig-obj on windows-gnu targets which fixes the error, based on the advice [here](https://digitalkarabela.com/mingw-w64-how-to-fix-file-too-big-too-many-sections/). I have tested this with both the x86_64-pc-windows-gnu and i686-pc-windows-gnu targets.
=> Add -mbig-obj flag when building harfbuzz on windows-gnu

harfbuzz-sys/Cargo.toml
We shouldn't need any of the test stuff, the benchmark library, or docs from harfbuzz in the package on crates.io.
The previous exclusion block was very incomplete for the version of harfbuzz provided.
=> harfbuzz-sys: Exclude more from published package.

.github/workflows/main.yml
This peels 2 commits off of #211 since I think these are needed no matter what else happens.
=> Correct the name of the GitHub Actions jobs and make sure to test all static/shared combinations

harfbuzz-sys/Cargo.toml, harfbuzz-sys/LICENSE, harfbuzz-sys/README.md, harfbuzz/Cargo.toml, harfbuzz/LICENSE-APACHE, harfbuzz/LICENSE-MIT, harfbuzz/README.md
This also copies the license files so that the links for them should work and they'll be included in the packages via crates.io.
=> Add `README.md` to each crate.

harfbuzz-sys/Cargo.toml, harfbuzz-sys/README.md, harfbuzz-sys/src/coretext.rs, harfbuzz-sys/src/directwrite.rs, harfbuzz-sys/src/lib.rs, harfbuzz/Cargo.toml, harfbuzz/README.md, harfbuzz/src/lib.rs
Now, the feature for this is called `freetype` rather than `build-native-freetype`. This was never building FreeType but just saying to build with FreeType and to use `freetype-sys`.
The default features were disabled for `freetype` and then enabling the `freetype-sys` feature, but that's exactly what the `freetype` crate does by default, so simplify by not trying to do it again.
Partial fix for #184 (this doesn't handle the `coretext` side).
=> Do better with platform (font engine) features.

.github/workflows/main.yml, harfbuzz-sys/Cargo.toml, harfbuzz-sys/README.md, harfbuzz-sys/build.rs, harfbuzz-sys/src/lib.rs, harfbuzz/Cargo.toml, harfbuzz/README.md, harfbuzz/src/lib.rs
This looks for one installed on the system by default. It can be forced to look on the system even if `bundled` is set by defining `HARFBUZZ_SYS_USE_PKG_CONFIG` in the environment to `"1"`.
If `bundled` is set, then it will use the sources that we vendor.
In general, `bundled` should be set as needed by applications rather than by libraries using `harfbuzz` or `harfbuzz-sys`. This allows for control by the application's build since once the feature is enabled by a crate, it can't readily be disabled.
The name for the `bundled` feature comes from the rusqlite bindings for `libsqlite-sys`.
=> Use `bundled` feature to use our own copy of harfbuzz.

harfbuzz-sys/src/freetype.rs, harfbuzz-sys/src/lib.rs
This makes it more like the others, and will keep it cleaner when we go and bind the other functions in this module.
=> Move freetype binding to separate module.

harfbuzz-sys/build.rs
When we build a bundled `harfbuzz`, only enable `HAVE_CORETEXT` and `HAVE_DIRECTWRITE` when the corresponding features are set.
We don't correct `HAVE_FREETYPE` here as it has other larger issues that need to be resolved first.
=> bundled: Obey coretext, directwrite features when configuring harfbuzz.

harfbuzz/src/lib.rs, harfbuzz/src/version.rs
This will be useful moving forward as we start to update the library version.
=> Add wrappers for the `hb_version*` functions.

.github/workflows/main.yml, harfbuzz-sys/src/lib.rs, harfbuzz/Cargo.toml, harfbuzz/src/blob.rs, harfbuzz/src/buffer.rs, harfbuzz/src/language.rs, harfbuzz/src/lib.rs
Adds a `std` feature, enabled by default, to `harfbuzz` to enable one API that needs `std::sync::Arc`.
=> Make harfbuzz and harfbuzz-sys no_std

harfbuzz-sys/Cargo.toml, harfbuzz-sys/src/freetype.rs
This simplifies the dependency graph as we weren't getting anything from using the Servo `freetype` crate here as it also built and depended upon `freetype-sys`.
Fixes #238.
=> Use `freetype-sys` rather than Servo's `freetype`.

harfbuzz-sys/Cargo.toml
This is in preparation for the 0.6.0 release.
=> dependencies: Upgrade to the latest version of freetype-sys

harfbuzz-sys/Cargo.toml
Update freetype-sys to v0.20.1 for an OpenHarmony build fix.
=> Bump freetype-sys to v0.20.1

Cargo.toml, harfbuzz-sys/Cargo.toml, harfbuzz-traits/Cargo.toml, harfbuzz/Cargo.toml
I managed to publish this crate without checking out the git submodules
first, which breaks the `bundled` build. This version bump will ensure
that the latest version on crates.io can build.
=> Release a version 0.6.1 of `harfbuzz` and consolidate Cargo configuration

harfbuzz/src/blob.rs
These are from nightly clippy. Prefer using associated constants rather than some of the older functions and constants as they are likely to be deprecated in the future.
=> harfbuzz: Fix `legacy_numeric_constants` lints.

.github/workflows/main.yml, README.md, harfbuzz-sys/Cargo.toml
Integrate https://github.com/PistonDevelopers/freetype-sys/commit/b7857227152dc095df6d644918e0ba5335e40ccc.
=> deps: Upgrade `freetype-sys` to version 0.21
