servo/rust-harfbuzz

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/49)

Notify Homu of travis changes

---

Cargo.toml
build.rs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/47)

use NUM_JOBS to control make -j

---

Cargo.toml

r? @metajack
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/52)

Bump cargo version number

---

harfbuzz-sys/Cargo.toml

CC https://github.com/servo/servo/pull/8446
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/55)

Update to libc 0.2

---

harfbuzz-sys/Cargo.toml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/59)

Release version 0.1.3

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/62)

Release version 0.1.5

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/64)

Bump version number.

---

harfbuzz-sys/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/66)

(Do not merge) Do not explicitly link against the C++ std library

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/67)

Bump version to 0.1.7

---

harfbuzz-sys/makefile.cargo

Required for https://github.com/servo/servo/issues/11921
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/71)

Fix armv7-linux-androideabi compilation

---

harfbuzz-sys/Cargo.toml
harfbuzz-sys/src/lib.rs

Fixes https://github.com/servo/rust-harfbuzz/issues/70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/72)

Change freetype dependency

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/74)

Bump version to 0.1.11

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/77)

Bump freetype version.

---

harfbuzz-sys/Cargo.toml
harfbuzz-sys/makefile.cargo

Fix #79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/80)

disable .so files

---

harfbuzz-sys/Cargo.toml
harfbuzz-sys/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/81)

 Set MAKEFLAGS to CARGO_MAKEFLAGS for the make command 

---

harfbuzz-sys/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/97)

Update for bindgen change to the generated text.

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/100)

Set up appveyor.

---

harfbuzz-sys/build.rs
harfbuzz-sys/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/104)

Run rustfmt.

---

harfbuzz-sys/Cargo.toml
harfbuzz/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/107)

Update to freetype 0.4.

---

harfbuzz-sys/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/108)

Re-run build script if environment changes

---

harfbuzz/src/blob.rs
harfbuzz/src/language.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/116)

High-level improvements

---

harfbuzz-sys/build.rs

Fixes #117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/118)

Link in stdc++ when building on Windows GNU

---

harfbuzz-sys/Cargo.toml
harfbuzz-sys/makefile.cargo
harfbuzz/Cargo.toml

Makes it possible to build with clang for Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/119)

Build with clang on ARM/Android

---

harfbuzz-sys/Cargo.toml
harfbuzz/Cargo.toml

This includes #126 and #127 which only add new APIs, and #129 which adds new features but uses them by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/130)

Release 0.3.1.

---

harfbuzz/src/blob.rs

Fixes #131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/132)

Improve safety of the Blob abstraction.

---

harfbuzz-sys/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/145)

Publish 0.3.2

---

harfbuzz-sys/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/151)

Update some docs from upstream.

---

harfbuzz-sys/build.rs
harfbuzz-sys/src/coretext.rs
harfbuzz/src/blob.rs
harfbuzz/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/154)

Run cargo fmt.

---

harfbuzz-sys/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/160)

Switch from cfg_attr to clippy:: syntax.

---

harfbuzz-sys/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-harfbuzz/168)

Add missing hb_color_get_* bindings.

---

harfbuzz-sys/Cargo.toml

Publish the changes from https://github.com/servo/rust-harfbuzz/pull/170.

Update harfbuzz-sys to 0.3.4.

---

.github/workflows/main.yml

These only build and don't run tests.

ci: Add jobs for aarch64-apple-ios, wasm32-unknown-emscripten

---

harfbuzz-sys/Cargo.toml
harfbuzz-traits/Cargo.toml
harfbuzz/Cargo.toml

This updates the version and syncs them in preparation for a new
release.

Release version 0.6.0 of all crates

---

harfbuzz-sys/Cargo.toml
harfbuzz-sys/src/directwrite.rs

Closes https://github.com/servo/rust-harfbuzz/issues/256

refactor: use windows instead of winapi

---

harfbuzz-sys/Cargo.toml

Signed-off-by: Martin Robinson <mrobinson@igalia.com>

Upgrade to the `freetype-sys` 0.23.0
